#include "3.1/pkcs11.h"

#define NISEC_VENDOR_NSS 0x4E534543 /* NSEC */

#define CKM_NISEC (CKM_VENDOR_DEFINED | NISEC_VENDOR_NSS)
#define CKP_NISEC (CKP_VENDOR_DEFINED | NISEC_VENDOR_NSS)
#define CKK_NISEC (CKK_VENDOR_DEFINED | NISEC_VENDOR_NSS)

#define CKK_ML_DSA (CKK_NISEC + 1)
#define CKM_ML_DSA_KEYGEN (CKM_NISEC + 2)
#define CKM_ML_DSA (CKM_NISEC + 3)

/* CKA_PARAMETER_SET is new for v3.2 */
#define CKA_PARAMETER_SET 0x0000061DUL

/* ML-DSA values for CKA_PARAMETER_SETS */
#define CKP_ML_DSA_44 0x00000001UL
#define CKP_ML_DSA_65 0x00000002UL
#define CKP_ML_DSA_87 0x00000003UL
